# Generated by Django 5.0 on 2023-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.TextField()),
                ('gender', models.TextField()),
                ('addr', models.TextField()),
            ],
        ),
    ]
